server:
  port: 80

eureka:
  client:
    service-url:
      register-with-eureka: false
      defaultZone: http://eureka1.com:7001/eureka/
#      ,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/

service:
  name: SPRINGCLOUD-SERVICE-NEWS