server:
  port: 8002

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.mark.springcloud.pojo

spring:
  application:
    name: springcloud-service-user
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_user
    username: root
    password: 290134
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-server-user${server.port}
    prefer-ip-address: true

info:
  app.name: springcloud-service-user
  company.name: www.mark.com
  build.artifactId: springcloud-service-user
  build.version: 1.0-SNAPSHOT
management:
  endpoints:
    web:
      exposure:
        include: "*"